new_deck = Deck.create(name: "State Capitols")
new_deck.Card.create(term: "Sacramento", description: "California")
new_deck.Card.create(term: "Salem", description: "Oregon")
new_deck.Card.create(term: "Olympia", description: "Washington")
new_deck.Card.create(term: "Atlanta", description: "Georgia")
new_deck.Card.create(term: "Denver", description: "Colorado")
new_deck.Card.create(term: "Honolulu", description: "Hawaii")


new_deck = Deck.create(name: "Futurama Characters")
new_deck.Card.create(term: "Leela", description: "Awesome Cylcops space captain")
new_deck.Card.create(term: "Bender", description: "Rude beer-fueled machine")
new_deck.Card.create(term: "Hermes", description: "Rastafarian accountant")
new_deck.Card.create(term: "Fry", description: "Frozen delivery boy from 1999")
new_deck.Card.create(term: "URL", description: "Robot cop")
new_deck.Card.create(term: "Horrible Gelatinous Blob", description: "Large translucent acidic alien")


new_deck = Deck.create(name: "Trees")
new_deck.Card.create(term: "Ginko", description: "Fan-shaped leaves, common in Eastern medecine")
new_deck.Card.create(term: "Bristlecone pine", description: "Oldest non-clonal tree")
new_deck.Card.create(term: "Redwood", description: "Tallest tree in the world")
new_deck.Card.create(term: "Magnolia", description: "Huge white blooms, common in the Southern USA")
new_deck.Card.create(term: "Willow", description: "Long strands of oval leaves, sometimes weeping")
new_deck.Card.create(term: "Apricot", description: "Known for their apricots")
